#!/usr/bin/env python3


from pathlib import Path


filename = Path(__file__).name
content = (
    "// \n"
    "// All Marinette themes are there\n"
    f"// Auto generated by {filename}\n"
    "\n\n\n\n"
    "Themes = {}\n"
)
srcs = list(Path("themes").iterdir())
srcs.sort()
for src in srcs:
    with open(src, "r") as fd:
        content = content + ("\n"*2) + fd.read()
with open("src/themeing.src", "w") as fd:
    fd.write(content)
