#!/usr/bin/env python3


from pathlib import Path


filename = Path(__file__).name
content = (
    "//\n"
    "// Portable programs that are easily integratable are here\n"
    f"// Auto generated by {filename}\n"
    "\n\n"
)
srcs = list(Path("integrated").iterdir())
srcs.sort()
for src in srcs:
    with open(src, "r") as fd:
        content = content + ("\n"*2) + fd.read()
with open("src/integrated.src", "w") as fd:
    fd.write(content)
