#!/usr/bin/env python3


from pathlib import Path


filename = Path(__file__).name
content = (
    "// \n"
    "// All Marinette locales are there\n"
    f"// Auto generated by {filename}\n"
    "\n\n\n\n"
    "Locales = {}\n"
)
footer = str()
srcs = list(Path("locales").iterdir())
srcs.sort()
for src in srcs:
    with open(src, "r") as fd:
        footer = footer + ("\n"*4) + fd.read()

for line in footer.split("\n"):
    entry = line.strip()
    if not entry or entry[0:2] == "//":
        continue
    if "_language =" in entry and entry != "_language = \"English\"":
        break
    entry = entry.replace("[_language]", "")
    entryName, *_ = entry.split(" ")
    entryName = entryName.strip()
    if entryName == "_language":
        continue
    content = content + entryName + " = {}\n"

content = content + footer
with open("src/localization.src", "w") as fd:
    fd.write(content)
